/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package togo;

import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.view.mxGraph;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Alexy jr
 */
public class TOGO extends javax.swing.JFrame {

    /**
     * Creates new form TOGO
     */
    public TOGO() {
        initComponents();
        setLocationRelativeTo(this);
        //this.setExtendedState(MAXIMIZED_BOTH);
        Red = new Grafo();
        Red.addVertice(central);

        Analisis = new Grafo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jd_mapa = new javax.swing.JDialog();
        jp_mapa = new javax.swing.JPanel();
        jd_modificar_eliminar_rc = new javax.swing.JDialog();
        cb_routers_modificar = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cb_tipo_r_modificar = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        tf_num_serie_modificar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jd_mapa_analisis1 = new javax.swing.JDialog();
        jp_mapa_analisis1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jd_mapa_analisis2 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_floyd = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jd_mapa_analisis3 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_prim = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        cb_tipo_router = new javax.swing.JComboBox();
        cb_vertices1 = new javax.swing.JComboBox();
        cb_vertices2 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_longitud_cable = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_ancho_banda = new javax.swing.JTextField();
        rb_cable_cobre = new javax.swing.JRadioButton();
        rb_cable_fibra = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        tf_num_serie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonTask1 = new org.edisoncor.gui.button.ButtonTask();
        buttonTask2 = new org.edisoncor.gui.button.ButtonTask();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_mapa = new javax.swing.JMenuItem();
        jmi_modificar_eliminar = new javax.swing.JMenuItem();
        jm_analisis = new javax.swing.JMenu();
        jmi_r = new javax.swing.JMenuItem();
        jmi_p = new javax.swing.JMenuItem();
        jmi_m = new javax.swing.JMenuItem();

        jd_mapa.setResizable(false);
        jd_mapa.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jd_mapaWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout jp_mapaLayout = new javax.swing.GroupLayout(jp_mapa);
        jp_mapa.setLayout(jp_mapaLayout);
        jp_mapaLayout.setHorizontalGroup(
            jp_mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        jp_mapaLayout.setVerticalGroup(
            jp_mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_mapaLayout = new javax.swing.GroupLayout(jd_mapa.getContentPane());
        jd_mapa.getContentPane().setLayout(jd_mapaLayout);
        jd_mapaLayout.setHorizontalGroup(
            jd_mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_mapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_mapaLayout.setVerticalGroup(
            jd_mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_mapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jd_modificar_eliminar_rc.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jd_modificar_eliminar_rc.getContentPane().add(cb_routers_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 63, 282, -1));

        jButton4.setText("Eliminar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jd_modificar_eliminar_rc.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 62, 144, -1));

        jButton5.setText("Cambiar a");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jd_modificar_eliminar_rc.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 112, 144, -1));

        cb_tipo_r_modificar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Repetidor de red domestica", "Repetidor de red empresarial", "Antena celular", "Conexion dedicada" }));
        jd_modificar_eliminar_rc.getContentPane().add(cb_tipo_r_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 113, 282, -1));

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Numero de serie");
        jd_modificar_eliminar_rc.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));
        jd_modificar_eliminar_rc.getContentPane().add(tf_num_serie_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 153, 119, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dark-blue-texture-wallpaper-wide.jpg"))); // NOI18N
        jd_modificar_eliminar_rc.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 350));

        jd_mapa_analisis1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jd_mapa_analisis1WindowClosed(evt);
            }
        });

        javax.swing.GroupLayout jp_mapa_analisis1Layout = new javax.swing.GroupLayout(jp_mapa_analisis1);
        jp_mapa_analisis1.setLayout(jp_mapa_analisis1Layout);
        jp_mapa_analisis1Layout.setHorizontalGroup(
            jp_mapa_analisis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_mapa_analisis1Layout.setVerticalGroup(
            jp_mapa_analisis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_mapa_analisis1Layout = new javax.swing.GroupLayout(jd_mapa_analisis1.getContentPane());
        jd_mapa_analisis1.getContentPane().setLayout(jd_mapa_analisis1Layout);
        jd_mapa_analisis1Layout.setHorizontalGroup(
            jd_mapa_analisis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mapa_analisis1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_mapa_analisis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jp_mapa_analisis1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
                .addContainerGap())
        );
        jd_mapa_analisis1Layout.setVerticalGroup(
            jd_mapa_analisis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mapa_analisis1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_mapa_analisis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jd_mapa_analisis2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jta_floyd.setColumns(20);
        jta_floyd.setRows(5);
        jScrollPane1.setViewportView(jta_floyd);

        jd_mapa_analisis2.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 380, 278));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dark-blue-texture-wallpaper-wide.jpg"))); // NOI18N
        jd_mapa_analisis2.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        jta_prim.setColumns(20);
        jta_prim.setRows(5);
        jScrollPane2.setViewportView(jta_prim);

        javax.swing.GroupLayout jd_mapa_analisis3Layout = new javax.swing.GroupLayout(jd_mapa_analisis3.getContentPane());
        jd_mapa_analisis3.getContentPane().setLayout(jd_mapa_analisis3Layout);
        jd_mapa_analisis3Layout.setHorizontalGroup(
            jd_mapa_analisis3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mapa_analisis3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_mapa_analisis3Layout.setVerticalGroup(
            jd_mapa_analisis3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mapa_analisis3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TOGO MAPPER ©");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("PRUEBAS");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 404, -1, -1));

        cb_tipo_router.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Repetidor de red domestica", "Repetidor de red empresarial", "Antena celular", "Conexion dedicada" }));
        getContentPane().add(cb_tipo_router, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 49, 200, -1));

        getContentPane().add(cb_vertices1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 242, 251, -1));

        getContentPane().add(cb_vertices2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 242, 264, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 598, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("ROUTERS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("CONEXIONES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 210, -1, -1));

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Longitud de cable");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 283, -1, -1));
        getContentPane().add(tf_longitud_cable, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 280, 102, -1));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Ancho de banda");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));
        getContentPane().add(tf_ancho_banda, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 281, 91, -1));

        buttonGroup1.add(rb_cable_cobre);
        rb_cable_cobre.setForeground(new java.awt.Color(240, 240, 240));
        rb_cable_cobre.setText("Cable de cobre");
        getContentPane().add(rb_cable_cobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        buttonGroup1.add(rb_cable_fibra);
        rb_cable_fibra.setForeground(new java.awt.Color(240, 240, 240));
        rb_cable_fibra.setText("Cable de fibra");
        getContentPane().add(rb_cable_fibra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Numero de serie");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));
        getContentPane().add(tf_num_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 89, 112, -1));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("MB/S");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        buttonTask1.setForeground(new java.awt.Color(240, 240, 240));
        buttonTask1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add-icon.png"))); // NOI18N
        buttonTask1.setText("Añadir router");
        buttonTask1.setDescription("Crea un router para TOGO");
        buttonTask1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTask1MouseClicked(evt);
            }
        });
        getContentPane().add(buttonTask1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, -1));

        buttonTask2.setForeground(new java.awt.Color(240, 240, 240));
        buttonTask2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add-icon.png"))); // NOI18N
        buttonTask2.setText("Añadir conexion");
        buttonTask2.setDescription("Conecta dos routers");
        buttonTask2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTask2MouseClicked(evt);
            }
        });
        getContentPane().add(buttonTask2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dark-blue-texture-wallpaper-wide.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        jm_archivo.setText("Archivo");

        jmi_mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/map-icon.gif"))); // NOI18N
        jmi_mapa.setText("Ver mapa");
        jmi_mapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mapaActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_mapa);

        jmi_modificar_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_edit_topic.gif"))); // NOI18N
        jmi_modificar_eliminar.setText("Modificar/Eliminar");
        jmi_modificar_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificar_eliminarActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_modificar_eliminar);

        jMenuBar1.add(jm_archivo);

        jm_analisis.setText("Analisis");

        jmi_r.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/router2.jpg"))); // NOI18N
        jmi_r.setText("Router a router");
        jmi_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_rActionPerformed(evt);
            }
        });
        jm_analisis.add(jmi_r);

        jmi_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ancho_banda.gif"))); // NOI18N
        jmi_p.setText("Probar ancho de banda");
        jmi_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pActionPerformed(evt);
            }
        });
        jm_analisis.add(jmi_p);

        jmi_m.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cables.png"))); // NOI18N
        jmi_m.setText("Minima cantidad de cable");
        jmi_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mActionPerformed(evt);
            }
        });
        jm_analisis.add(jmi_m);

        jMenuBar1.add(jm_analisis);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Red.print();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jmi_mapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mapaActionPerformed
        // TODO add your handling code here:
        DibujarGrafo(Red);

        jd_mapa.setModal(true);
        jd_mapa.pack();
        jd_mapa.setLocationRelativeTo(this);
        jd_mapa.setVisible(true);
    }//GEN-LAST:event_jmi_mapaActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        int pos = cb_routers_modificar.getSelectedIndex();
        Red.deleteVertice(pos);
        vertices_temp.erase(pos);

        cb_routers_modificar.removeAllItems();
        cb_vertices1.removeAllItems();
        cb_vertices2.removeAllItems();

        for (int i = 0; i < vertices_temp.size(); i++) {
            cb_routers_modificar.addItem(((Vertice) (vertices_temp.at(i))));
            cb_vertices1.addItem(((Vertice) (vertices_temp.at(i))));
            cb_vertices1.addItem(((Vertice) (vertices_temp.at(i))));
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        int pos = cb_routers_modificar.getSelectedIndex();
        String nombre = cb_tipo_r_modificar.getSelectedItem().toString();
        int num_serie = Integer.parseInt(tf_num_serie_modificar.getText());

        ((Vertice) Red.getVertices().at(pos)).setNombre(nombre);
        ((Vertice) Red.getVertices().at(pos)).setNumero_serie(num_serie);

        ((Vertice) vertices_temp.at(pos)).setNombre(nombre);
        ((Vertice) vertices_temp.at(pos)).setNumero_serie(num_serie);

        cb_routers_modificar.removeAllItems();
        cb_vertices1.removeAllItems();
        cb_vertices2.removeAllItems();

        for (int i = 0; i < vertices_temp.size(); i++) {
            cb_routers_modificar.addItem(((Vertice) (vertices_temp.at(i))));
            cb_vertices1.addItem(((Vertice) (vertices_temp.at(i))));
            cb_vertices1.addItem(((Vertice) (vertices_temp.at(i))));
        }

        tf_num_serie_modificar.setText("");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jmi_modificar_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificar_eliminarActionPerformed
        // TODO add your handling code here:
        jd_modificar_eliminar_rc.setModal(true);
        jd_modificar_eliminar_rc.pack();
        jd_modificar_eliminar_rc.setLocationRelativeTo(this);
        jd_modificar_eliminar_rc.setVisible(true);
    }//GEN-LAST:event_jmi_modificar_eliminarActionPerformed

    private void jmi_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_rActionPerformed
        // TODO add your handling code here:
        Recorridos = new Lista();
        Lista nombres = new Lista();
        BuscarNodo(new CaminoMinimo(((Vertice) cb_vertices1.getSelectedItem()).getNombre()), ((Vertice) cb_vertices2.getSelectedItem()).getNombre());
        if (Recorridos.size() > 0) {
            if (true) {
                CaminoMinimo resultado = new CaminoMinimo("");
                for (int i = 0; i < Recorridos.size(); i++) {
                    if (resultado.getCoste() > ((CaminoMinimo) Recorridos.at(i)).getCoste() || resultado.getCoste() == -1) {
                        resultado = (CaminoMinimo) Recorridos.at(i);
                    }
                }

                String m[] = resultado.ToString();
                jTextField1.setText(m[0] + m[1]);
                RRecorridos.push_back(resultado);

                for (int i = 0; i < resultado.getNombres().size(); i++) {
                    nombres.push_back(resultado.getNombres().at(i));
                }
            }
        }

        for (int i = 0; i < Red.getVertices().size(); i++) {
            for (int j = 0; j < nombres.size(); j++) {
                if (nombres.at(j).toString().equals(((Vertice) Red.getVertices().at(i)).getNombre())) {
                    Analisis.addVertice((Vertice) Red.getVertices().at(i));
                }
            }
        }

        Analisis.print();
        DibujarGrafoTemporal(Analisis, jp_mapa_analisis1);

        jd_mapa_analisis1.setModal(true);
        jd_mapa_analisis1.pack();
        jd_mapa_analisis1.setLocationRelativeTo(this);
        jd_mapa_analisis1.setVisible(true);
    }//GEN-LAST:event_jmi_rActionPerformed

    private void jd_mapaWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_mapaWindowClosed
        // TODO add your handling code here:
        cmp.removeAll();
    }//GEN-LAST:event_jd_mapaWindowClosed

    private void jd_mapa_analisis1WindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_mapa_analisis1WindowClosed
        // TODO add your handling code here:
        cmp_temp.removeAll();
        for (int i = 0; i < Analisis.getVertices().size(); i++) {
            Analisis.deleteVertice(i);
        }
    }//GEN-LAST:event_jd_mapa_analisis1WindowClosed

    private void jmi_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pActionPerformed
        // TODO add your handling code here:

        String Floyd = Red.floyd(Red.generarMatrizAdyacencia());

        Object[][] matriz_temp = Red.getMatriz_vertices();
        String matriz_vertices = "\n";
        for (int i = 0; i < matriz_temp.length; i++) {
            for (int j = 0; j < matriz_temp.length; j++) {
                if (matriz_temp[i][j] == null) {
                    matriz_vertices += "[NULL]";
                } else {
                    matriz_vertices += "[" + ((Vertice) matriz_temp[i][j]).getNombre() + "] ";
                }
            }
            matriz_vertices += "\n";
        }

        jta_floyd.setText(Floyd + matriz_vertices);

        jd_mapa_analisis2.setModal(true);
        jd_mapa_analisis2.pack();
        jd_mapa_analisis2.setLocationRelativeTo(this);
        jd_mapa_analisis2.setVisible(true);
    }//GEN-LAST:event_jmi_pActionPerformed

    private void jmi_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mActionPerformed
        // TODO add your handling code here:

        long[][] matriz_temp = Red.AlgPrim(Red.generarMatrizAdyacencia());
        String matriz_vertices = "\n";
        for (int i = 0; i < matriz_temp.length; i++) {
            for (int j = 0; j < matriz_temp.length; j++) {
                if (matriz_temp[i][j] == 0) {
                    matriz_vertices += "[NULL]";
                } else {
                    matriz_vertices += "[" + matriz_temp[i][j] + "]";
                }
            }
            matriz_vertices += "\n";
        }

        jta_prim.setText(matriz_vertices);

        jd_mapa_analisis3.setModal(true);
        jd_mapa_analisis3.pack();
        jd_mapa_analisis3.setLocationRelativeTo(this);
        jd_mapa_analisis3.setVisible(true);
    }//GEN-LAST:event_jmi_mActionPerformed

    private void buttonTask1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTask1MouseClicked
        // TODO add your handling code here:
        if (!tf_num_serie.getText().equals("")) {
            String nombre = cb_tipo_router.getSelectedItem().toString();
            int numero_serie = Integer.parseInt(tf_num_serie.getText());
            Lista temp = new Lista();

            Vertice v = new Vertice(nombre, temp, numero_serie);
            Red.addVertice(v);
            vertices_temp.push_back(v);

            cb_vertices1.addItem(v);
            cb_vertices2.addItem(v);
            cb_routers_modificar.addItem(v);
        } else if (Nombre_tecnico.equals("") && tf_num_serie.getText().equals("")) {
            Nombre_tecnico = JOptionPane.showInputDialog("Escribe tu nombre porfavor");
        }

        if (tf_num_serie.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Estimado " + Nombre_tecnico + " trataste de instalar un router sin numero de serie " + "\n"
                    + "se mandara un reporte de tu falla a la oficina central de TOGO" + "\n"
                    + "¡sonrie, tienes TOGO!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        tf_num_serie.setText("");
    }//GEN-LAST:event_buttonTask1MouseClicked

    private void buttonTask2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTask2MouseClicked
        // TODO add your handling code here:
        Vertice temp1 = ((Vertice) cb_vertices1.getSelectedItem());
        Vertice temp2 = ((Vertice) cb_vertices2.getSelectedItem());

        if (temp1.equals(temp2) && Nombre_tecnico.equals("")) {
            Nombre_tecnico = JOptionPane.showInputDialog("Escribe tu nombre porfavor");
        } else if ((!temp1.equals(temp2))) {
            int Ancho_banda = Integer.parseInt(tf_ancho_banda.getText());
            int Longitud_cable = Integer.parseInt(tf_longitud_cable.getText());

            if (rb_cable_cobre.isSelected()) {
                if (Ancho_banda > 0 && Ancho_banda <= 100) {
                    Arista a = new Arista(temp1, temp2, Longitud_cable, Ancho_banda);
                    Arista b = new Arista(temp2, temp1, Longitud_cable, Ancho_banda);

                    temp1.addArista(b);
                    temp2.addArista(a);

                    aristas_temp.push_back(a);
                    aristas_temp.push_back(b);

                    if (Conectar_central == 0) {
                        Arista c1 = new Arista(temp1, central, Longitud_cable, Ancho_banda);
                        Arista c2 = new Arista(central, temp1, Longitud_cable, Ancho_banda);
                        central.addArista(c1);
                        temp1.addArista(c2);

                        Conectar_central++;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error al establecer la conexion",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else if (rb_cable_fibra.isSelected()) {
                if (Ancho_banda > 0 && Ancho_banda <= 10000) {
                    Arista a = new Arista(temp1, temp2, Longitud_cable, Ancho_banda);
                    Arista b = new Arista(temp2, temp1, Longitud_cable, Ancho_banda);

                    temp1.addArista(b);
                    temp2.addArista(a);

                    aristas_temp.push_back(a);
                    aristas_temp.push_back(b);

                    if (Conectar_central == 0) {
                        Arista c1 = new Arista(temp1, central, Longitud_cable, Ancho_banda);
                        Arista c2 = new Arista(central, temp1, Longitud_cable, Ancho_banda);
                        central.addArista(c1);
                        temp1.addArista(c2);

                        Conectar_central++;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error al establecer la conexion",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }

            tf_ancho_banda.setText("");
            tf_longitud_cable.setText("");
            rb_cable_cobre.setSelected(true);
        }

        if (temp1.equals(temp2) && !Nombre_tecnico.equals("")) {
            JOptionPane.showMessageDialog(this, "Estimado " + Nombre_tecnico
                    + " un router no puede ser conectado a si mismo, "
                    + "se te asiganara otro tecnico de ayuda" + "\n"
                    + "¡sonrie, tienes TOGO!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_buttonTask2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TOGO().setVisible(true);
            }
        });
    }

    public void BuscarNodo(CaminoMinimo recibir, String destino) {
        CaminoMinimo clon = recibir.clonar();
        recibir.delete();

        Vertice temp = null;

        for (int i = 0; i < Red.getVertices().size(); i++) {
            if (clon.getPath().get(recibir.getPath().size() - 1).equals(((Vertice) Red.getVertices().at(i)).getNombre())) {
                temp = ((Vertice) (Red.getVertices().at(i)));
            }
        }

        if (temp != null) {
            if (!(destino.equals(temp.getNombre()))) {
                if (temp.hasArista()) {
                    for (int i = 0; i < temp.getAristas().size(); i++) {
                        if (clon.buscar(((Arista) temp.getAristas().at(i)).getDestino().getNombre())) {
                            CaminoMinimo enviar = clon.clonar();
                            clon.delete();
                            enviar.addPath(((Arista) temp.getAristas().at(i)).getDestino().getNombre());
                            enviar.addG(((Arista) (temp.getAristas().at(i))).getLongitud());
                            BuscarNodo(enviar, destino);
                        }
                    }
                }
            } else {
                Recorridos.push_back(clon);
            }
        }

    }

    public void DibujarGrafo(Grafo grafo) {
        Object Parent = graph.getDefaultParent();
        cmp.setPreferredSize(new Dimension(800, 300));
        graph.getModel().beginUpdate();
        Lista temp2 = new Lista();
        Lista temp = new Lista();
        int y = 0;
        for (int i = 0; i < grafo.getVertices().size(); i++) {
            if (i % 3 == 0) {
                y = 100;
            } else {
                if (i % 3 == 1) {
                    y = 200;
                }
                if (i % 3 == 2) {
                    y = 0;
                }
            }
            temp2.push_back(graph.insertVertex(Parent, null, ((Vertice) Red.getVertices().at(i)).getNombre(), 70 * i, y, 50, 50));
            temp.push_back((Vertice) Red.getVertices().at(i));
        }
        Object Origen = null, Destino = null;
        for (int i = 0; i < grafo.getVertices().size(); i++) {
            try {
                for (int j = 0; j < ((Vertice) grafo.getVertices().at(i)).getAristas().size(); j++) {
                    int peso = ((Arista) ((Vertice) grafo.getVertices().at(i)).getAristas().at(j)).getBanda();
                    String Nombre1 = ((Arista) ((Vertice) Red.getVertices().at(i)).getAristas().at(j)).getInicio().getNombre();
                    String Nombre2 = ((Arista) ((Vertice) Red.getVertices().at(i)).getAristas().at(j)).getDestino().getNombre();
                    for (int k = 0; k < temp.size(); k++) {
                        if (Nombre1.equals(((Vertice) temp.at(k)).getNombre())) {
                            Origen = (Object) temp2.at(k);
                        }

                        if (Nombre2.equals(((Vertice) temp.at(k)).getNombre())) {
                            Destino = (Object) temp2.at(k);
                        }
                    }
                    graph.insertEdge(Parent, null, peso, Origen, Destino);
                }
            } catch (Exception e) {
            }
        }
        graph.getModel().endUpdate();
        jp_mapa.add(cmp);
        jp_mapa.setLayout(new FlowLayout());
    }

    public void DibujarGrafoTemporal(Grafo grafo, JPanel panel) {
        Object Parent = graph_temp.getDefaultParent();
        cmp_temp.setPreferredSize(new Dimension(800, 300));
        graph_temp.getModel().beginUpdate();
        Lista temp2 = new Lista();
        Lista temp = new Lista();
        int y = 0;
        for (int i = 0; i < grafo.getVertices().size(); i++) {
            if (i % 3 == 0) {
                y = 100;
            } else {
                if (i % 3 == 1) {
                    y = 200;
                }
                if (i % 3 == 2) {
                    y = 0;
                }
            }
            temp2.push_back(graph_temp.insertVertex(Parent, null, ((Vertice) Analisis.getVertices().at(i)).getNombre(), 70 * i, y, 50, 50));
            temp.push_back((Vertice) Analisis.getVertices().at(i));
        }
        Object Origen = null, Destino = null;
        for (int i = 0; i < grafo.getVertices().size(); i++) {
            try {
                for (int j = 0; j < ((Vertice) grafo.getVertices().at(i)).getAristas().size(); j++) {
                    int peso = ((Arista) ((Vertice) grafo.getVertices().at(i)).getAristas().at(j)).getBanda();
                    String Nombre1 = ((Arista) ((Vertice) Analisis.getVertices().at(i)).getAristas().at(j)).getInicio().getNombre();
                    String Nombre2 = ((Arista) ((Vertice) Analisis.getVertices().at(i)).getAristas().at(j)).getDestino().getNombre();
                    for (int k = 0; k < temp.size(); k++) {
                        if (Nombre1.equals(((Vertice) temp.at(k)).getNombre())) {
                            Origen = (Object) temp2.at(k);
                        }

                        if (Nombre2.equals(((Vertice) temp.at(k)).getNombre())) {
                            Destino = (Object) temp2.at(k);
                        }
                    }
                    graph_temp.insertEdge(Parent, null, peso, Origen, Destino);
                }
            } catch (Exception e) {
            }
        }
        graph_temp.getModel().endUpdate();
        panel.add(cmp_temp);
        panel.setLayout(new FlowLayout());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private org.edisoncor.gui.button.ButtonTask buttonTask1;
    private org.edisoncor.gui.button.ButtonTask buttonTask2;
    private javax.swing.JComboBox cb_routers_modificar;
    private javax.swing.JComboBox cb_tipo_r_modificar;
    private javax.swing.JComboBox cb_tipo_router;
    private javax.swing.JComboBox cb_vertices1;
    private javax.swing.JComboBox cb_vertices2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JDialog jd_mapa;
    private javax.swing.JDialog jd_mapa_analisis1;
    private javax.swing.JDialog jd_mapa_analisis2;
    private javax.swing.JDialog jd_mapa_analisis3;
    private javax.swing.JDialog jd_modificar_eliminar_rc;
    private javax.swing.JMenu jm_analisis;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenuItem jmi_m;
    private javax.swing.JMenuItem jmi_mapa;
    private javax.swing.JMenuItem jmi_modificar_eliminar;
    private javax.swing.JMenuItem jmi_p;
    private javax.swing.JMenuItem jmi_r;
    private javax.swing.JPanel jp_mapa;
    private javax.swing.JPanel jp_mapa_analisis1;
    private javax.swing.JTextArea jta_floyd;
    private javax.swing.JTextArea jta_prim;
    private javax.swing.JRadioButton rb_cable_cobre;
    private javax.swing.JRadioButton rb_cable_fibra;
    private javax.swing.JTextField tf_ancho_banda;
    private javax.swing.JTextField tf_longitud_cable;
    private javax.swing.JTextField tf_num_serie;
    private javax.swing.JTextField tf_num_serie_modificar;
    // End of variables declaration//GEN-END:variables
    Grafo Red;
    Grafo Analisis;

    Lista aristas_temp = new Lista();
    Lista vertices_temp = new Lista();
    Lista aristas_centrales = new Lista();
    Lista Recorridos = new Lista();
    Lista RRecorridos = new Lista();
    Vertice central = new Vertice("Router Central", aristas_centrales, 1);
    int Conectar_central = 0;
    String Nombre_tecnico = "";

    int y = 0;
    int x = 0;

    mxGraph graph = new mxGraph();
    mxGraphComponent cmp = new mxGraphComponent(graph);

    mxGraph graph_temp = new mxGraph();
    mxGraphComponent cmp_temp = new mxGraphComponent(graph_temp);
}
